spring.data.mongodb.uri=mongodb+srv://diegograndaest_db_user:OyZbPFyXhTWi6VhX@cluster0.fbixapm.mongodb.net/proyecto_tareas?retryWrites=true&w=majority&appName=Cluster0

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
